//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApplicationRodermel.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lesuser25Entities : DbContext
    {
        private static lesuser25Entities _context;

        public static lesuser25Entities GetContext()
        {
            if(_context == null)
                _context = new lesuser25Entities();
            return _context;
        }
        public lesuser25Entities()
            : base("name=lesuser25Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ученики> Ученики { get; set; }
    }
}
